---
title: "Economic Report"
author: "SEIGMA"
output: pdf_document
---


```{r income, echo=FALSE}
dat <- inc_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Median_Annual_Household_Income, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Median Annual Household Income", 
               x = "Mid-Year of Five Year Range",
               y = "Dollars") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```

```{r poverty, echo=FALSE}
dat <- pov_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Percent_Pov, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Poverty Rate", 
               x = "Mid-Year of Five Year Range",
               y = "% Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```

```{r employment, echo=FALSE}
dat <- emp_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Average_Monthly_Employment, group = Municipal, colour = Municipal)) + 
          geom_line(aes(linetype=Municipal), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Average Monthly Employment [Municipal]", 
               x = "Year",
               y = "Count") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))   
```

```{r unemployment, echo=FALSE}
dat <- une_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Unemployment_Rate_Avg, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Annual Average Unemployment Rate [No US Avg]", 
               x = "Year",
               y = "% Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))    
```


```{r Business Bankruptcy, echo=FALSE}
dat <- ban_df()
        var <- c("Chp.7_in_Business", "Chp.11_in_Business", "Chp.12_in_Business", "Chp.13_in_Business")
        bus <- c()
        if(input$buschp7)
          bus <- append(bus, var[1])
        if(input$buschp11)
          bus <- append(bus, var[2])
        if(input$buschp12)
          bus <- append(bus, var[3])
        if(input$buschp13)
          bus <- append(bus, var[4])
        dat <- filter(dat, variable %in% bus)
        dat$variable <- gsub("_in_Business", "", dat$variable)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Region, variable), colour = interaction(Region, variable))) +
          geom_line(aes(linetype=Region), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          labs(title = "Business Bankruptcy [County]", 
               x = "Year",
               y = "% Total Business Fillings") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12)) + 
          scale_color_discrete("Region")   
```


```{r Personal Bankruptcy, echo=FALSE}
dat <- ban_df()
        var <- c("Chp.7_in_Personal", "Chp.11_in_Personal", "Chp.13_in_Personal")
        per <- c()
        if(input$perchp7)
          per <- append(per, var[1])
        if(input$perchp11)
          per <- append(per, var[2])
        if(input$perchp13)
          per <- append(per, var[3])
        dat <- filter(dat, variable %in% per)
        dat$variable <- gsub("_in_Personal", "", dat$variable)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Region, variable), colour = interaction(Region, variable))) +
          geom_line(aes(linetype=Region), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          labs(title = "Personal Bankruptcy [County]", 
               x = "Year",
               y = "% Total Personal Fillings") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12)) + 
          scale_color_discrete("Region")    
```

```{r rent, echo=FALSE}
dat <- ren_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Median.Rent.2015.Dollar, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Median Monthly Rent(2015-$ Adjusted)", 
               x = "Mid-Year of Five Year Range",
               y = "Dollars") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```


```{r permits, echo=FALSE}
dat <- bui_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Permits_Per_1000_Population, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Building Permits per 1000 Population [No US]", 
               x = "Year",
               y = "Permits per 1000 Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```

```{r prop values, echo=FALSE}
dat <- val_df() 
        val_var <- as.character(unique(dat$variable))
        val <- c()
        if(input$resval)
          val <- append(val, val_var[1])
        if(input$comval)
          val <- append(val, val_var[2])
        if(input$indval)
          val <- append(val, val_var[3])
        if(input$perval)
          val <- append(val, val_var[4])
        dat <- filter(dat, variable %in% val)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Municipal, variable), colour = interaction(Municipal, variable))) +
          geom_line(aes(linetype=Municipal), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          labs(title = "Assessed Property Values[Municipal]", 
               x = "Year",
               y = "Dollars (million)") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))+ 
          scale_color_discrete("Municipal")
```

```{r tax by class, echo=FALSE}
dat <- tax_df() 
        tax_var <- as.character(unique(dat$variable))
        tax <- c()
        if(input$restax)
          tax <- append(tax, tax_var[1])
        if(input$comtax)
          tax <- append(tax, tax_var[2])
        if(input$indtax)
          tax <- append(tax, tax_var[3])
        if(input$pertax)
          tax <- append(tax, tax_var[4])
        dat <- filter(dat, variable %in% tax)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Municipal, variable), colour = interaction(Municipal, variable))) +
          geom_line(aes(linetype=Municipal), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          labs(title = "Tax Levy by Class [Municipal]", 
               x = "Year",
               y = "Dollars (million)") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))+ 
          scale_color_discrete("Municipal")
```

