---
title: "Social Report"
author: "SEIGMA"
---


```{r marital status, echo=FALSE}
    dat <- mar_df()
        status_var <- as.character(unique(dat$variable))
        status <- c()
        if(input$divorced)
          status <- append(status, status_var[5])
        if(input$married)
          status <- append(status, status_var[2])
        if(input$separated)
          status <- append(status, status_var[3])
        if(input$widowed)
          status <- append(status, status_var[4])
        if(input$never)
          status <- append(status, status_var[1])
        dat <- filter(dat, variable %in% status)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Region, variable), colour = interaction(Region, variable))) +
          geom_line(aes(linetype=Region), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          facet_grid(. ~ Gender) + 
          labs(title = "Marital Status", 
               x = "Mid-Year of Five Year Range",
               y = "% Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))+ 
          scale_color_discrete("Region")
```

```{r educational attainment, echo=FALSE}
    dat <- edu_df() 
        edu_var <- as.character(unique(dat$variable))
        edu <- c()
        if(input$hs)
          edu <- append(edu, edu_var[2])
        if(input$nohs)
          edu <- append(edu, edu_var[1])
        if(input$bac)
          edu <- append(edu, edu_var[3])
        if(input$grad)
          edu <- append(edu, edu_var[4])
        dat <- filter(dat, variable %in% edu)
        theme_set(theme_classic())
        ggplot(dat, aes(x = Year, y = value, group = interaction(Region, variable), colour = interaction(Region, variable))) +
          geom_line(aes(linetype=Region), size = 1.25, show.legend = FALSE) + 
          geom_point(size = 3) + 
          labs(title = "Educational Attainment", 
               x = "Mid-Year of Five Year Range",
               y = "% Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))+ 
          scale_color_discrete("Region")
```

```{r veterans, echo=FALSE}
    dat <- vet_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=value, group = Region, colour=Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Civilian Veterans Status", 
               x = "Mid-Year of Five Year Range",
               y = "% Population") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```

```{r suicide, echo=FALSE}
    dat <- sui_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Age.Adjusted.Rate, group = Region, colour = Region)) + 
          geom_line(aes(linetype=Region), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Suicide Rate (Age Adjusted) [County]", 
               x = "Year",
               y = "Per 100,000 Persons") + 
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```


```{r english learner, echo=FALSE}
   dat <- eng_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=English_Language_Learner, group = Municipal, colour = Municipal)) + 
          geom_line(aes(linetype=Municipal), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "English Language Learner [Municipal]", 
               x = "Year",
               y = "English Language Learner %") +  
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```

```{r disabilities, echo=FALSE}
    dat <- dis_df() 
        theme_set(theme_classic())
        ggplot(dat, aes(x=Year, y=Students_with_Disabilities, group = Municipal, colour = Municipal)) + 
          geom_line(aes(linetype=Municipal), size = 1.25) + 
          geom_point(size = 3) + 
          labs(title = "Students with Disabilities [Municipal]", 
               x = "Year",
               y = "Students with Disabilities %") +  
          theme(plot.title = element_text(face="bold", size=20, hjust=0)) +
          theme(axis.title = element_text(face="bold", size=18)) +
          theme(axis.text=element_text(size=14)) + 
          theme(legend.text = element_text(size = 12))
```